### ISSUE TITLE
Taxonomy tag url wrong

### ISSUE THREAD

**Issue by ghost** [Perlkonig/grav-plugin-tagcloud#2]
The generated URLs are wrong. 

The following doesn't help:
`{% include 'partials/tagcloud.html.twig' with {'base_url':new_base_url, 'taxonomy':'tag'} %}`

So I kind of fixed it for now but this might have to be fixed permanently for others too.

**Output:**
href="{{ base_url }}/tag{{ tax|e('url') }}

https://github.com/Perlkonig/grav-plugin-tagcloud/blob/365720a03394c7ee97078fad5d084591f3852c14/templates/partials/tagcloud.html.twig#L23

**Expected Output:**
href="{{ base_url }}/taxonomy?name=tag&val={{ tax|e('url') }}

Thanks!

**Comment by Perlkonig** [comment]
I think this is more a problem with my Knowledge Base theme than the plugin. The plugin syntax should work in most setups, and it really should work for the KB theme, too. I'll have to figure out why it's not. Thanks!

**Comment by Perlkonig** [comment]
Oh I remember now. Well, that's why it's so easy to override and customize 😄  This isn't something I can trivially make work everywhere. The current state is the one that will work on the most installs.

If I add this to the KB skeleton, then I'll include the template override so the user doesn't have to think about it.

**Comment by ghost** [comment]
Can you please make this optional in the plugin settings? So it would then support both ways but work instantly for users.

Thanks
